language: android
sudo: false
jdk: oraclejdk8

addons:
  sonarcloud:
    organization: "xrahul-github" # the key of the org you chose at step #3
    token:
      secure: "B6jqpUYRiz+HliCiwcmSqiSN2tsY+ifWj7y9U+N2j+k3yc8oV330BmAA0B9GLXRD+g2X8/OPwE+W2Ox1ow2nr+mxIDHwBRnylotszoF7UusCqg8H4qOXQiJHccZtJtYRTOlMZ4jlqA81nDoWBWe23i7Gotpw5XKnVPVeD5HaGJ3lOx7NJSKRTjs2UXOkhZU4cXNEHf+z33/rD7n1wbV/R87CAyq0z/5Gk4tdtkE24hEWlYbSRUrkBvGw1jep30t31ZzOFkyQmEvAv6HE7nBsE+Y++LSUwqDMjAIK3yHWdc9QAb86S5b9vOP3JQuQeA1jB4tcPc937RZdcKokOZPJgI7Hz1XGFQ8Ui4Pwpg8cQ137WeTZWmS6b04/v+Jkq+jYnPQ5obrezL1FHhAvz1x+WtoEXT4MLycSQ0djRXSMT3TwV7SQZgfdIR2dAx1qSiMa6KdmyOWUFMOI2V/qnzHhXB1o7Xmsufpn6VKF2gdI2KcEqHNhkU9oVDm+dzltEmF5vJKbMpoXyypwiAVG0rDnv+hVOjhJhGDOslcAZMAw/bPDiJVMQ/EoX+yfKso3F+Kio8jC3efsCWz5WSLkdRJnOgjGqFUL07nNoRPanL7vbUvkg5C0dws4dcLcVLuaiamyRKAEg2ZNbpuaUvEWhGqR+Yg4Fai9+DMDCa+AaJqlQCo="

android:
  components:
# Uncomment the lines below if you want to
# use the latest revision of Android SDK Tools
    - tools
    - platform-tools
    - tools

#    The BuildTools version used by your project
    - build-tools-23.0.3

#    The SDK version used to compile your project
    - android-23


    - extra
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-23
    - add-on
    - addon

#     Specify at least one system image,
#     if you need to run emulator(s) during your tests
#    - sys-img-arm64-v8a-google_apis-25
#    - sys-img-armeabi-v7a-google_apis-25

before_install:
- yes | sdkmanager "platforms;android-23"
- chmod +x gradlew

script:
  - ./gradlew assemble
  - ./gradlew clean build
  - ./gradlew build check
  - ./gradlew sonarqube

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
    - '$HOME/.android/build-cache'

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/